CafeRestaurant_/Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CafeRestaurant_.Data;
using CafeRestaurant_.Models;
using Microsoft.AspNetCore.Authorization;

namespace CafeRestaurant_.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize ]
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoryController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/Category
        public async Task<IActionResult> Index()
        {
            return View(await _context.Categories.ToListAsync());
        }

        // GET: Admin/Category/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Admin/Category/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Category/Create
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Admin/Category/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Admin/Category/Edit/5
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Admin/Category/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Admin/Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Categories.FindAsync(id);
            _context.Categories.Remove(category);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return _context.Categories.Any(e => e.Id == id);
        }
    }
}

CafeRestaurant_/Areas/Admin/Controllers/UserController.cs
using CafeRestaurant_.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace CafeRestaurant_.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _context;
        public UserController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var users = _context.ApplicationUsers.ToList();
            var role=_context.Roles.ToList();
            var userRole=_context.UserRoles.ToList();
            foreach(var item in users)
            {
                var roleId=userRole.FirstOrDefault(i=>i.UserId==item.Id).RoleId;
                item.Role=role.FirstOrDefault(u=>u.Id==roleId).Name;
            }
            return View(users);
        }
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.ApplicationUsers
                .FirstOrDefaultAsync(m => m.Id == id.ToString());
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Admin/Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var user = await _context.ApplicationUsers.FindAsync(id);
            _context.ApplicationUsers.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

CafeRestaurant_/Views/Shared/_Alayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Home</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="/Site/images/favicon-16x16.jpg" />
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/Site/vendor/bootstrap/css/bootstrap.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/Site/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/Site/fonts/themify/themify-icons.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/Site/vendor/animate/animate.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/Site/vendor/css-hamburgers/hamburgers.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/Site/vendor/animsition/css/animsition.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/Site/vendor/select2/select2.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/Site/vendor/daterangepicker/daterangepicker.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/Site/vendor/slick/slick.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/Site/vendor/lightbox2/css/lightbox.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/Site/css/util.css">
	<link rel="stylesheet" type="text/css" href="/Site/css/main.css">
	<!--===============================================================================================-->
</head>
<body class="animsition">

	<!-- Header -->
	<header>
		<!-- Header desktop -->
		<div class="wrap-menu-header gradient1 trans-0-4">
			<div class="container h-full">
				<div class="wrap_header trans-0-3">
					<!-- Logo -->
					<div class="logo">
						<a href="index.html">
							<img src="/Site/images/logo3.png" alt="IMG-LOGO" data-logofixed="/Site/images/logo3.png" style="width: 110px; height: auto;">
						</a>
					</div>

					<!-- Menu -->
					<div class="wrap_menu p-l-45 p-l-0-xl">
						<nav class="menu">
							<ul class="main_menu">
								@if (User.Identity.IsAuthenticated)
								{
									<li>
										<a asp-area="Customer" asp-controller="Home" asp-action="Index">HOME</a>
									</li>

									<li>
										<a asp-area="Customer" asp-controller="Home" asp-action="Menu">MENU</a>
									</li>

									<li>
										<a asp-area="Customer" asp-controller="Home" asp-action="Reservation">RESERVATION</a>
									</li>

									<li>
										<a asp-area="Customer" asp-controller="Home" asp-action="Gallery">GALLERY</a>
									</li>
									<li>
										<a asp-area="Admin" asp-controller="Menu" asp-action="Index" target="_blank">ADMIN PANEL</a>
									</li>
									<li >
										<form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
											<button type="submit" class="nav-link btn btn-link text-white">LOG OUT</button>
										</form>
									</li>
								}
								else
								{
									<li>
										<a asp-area="Customer" asp-controller="Home" asp-action="Index">HOME</a>
									</li>

									<li>
										<a asp-area="Customer" asp-controller="Home" asp-action="Menu">MENU</a>
									</li>

									<li>
										<a asp-area="Customer" asp-controller="Home" asp-action="Reservation">RESERVATION</a>
									</li>

									<li>
										<a asp-area="Customer" asp-controller="Home" asp-action="Gallery">GALLERY</a>
									</li>
									<li>
										<a asp-area="Customer" asp-controller="Home" asp-action="About">ABOUT</a>
									</li>

									<li>
										<a asp-area="Customer" asp-controller="Home" asp-action="Blog">BLOG</a>
									</li>

									<li>
										<a asp-area="Customer" asp-controller="Home" asp-action="Contact">CONTACT</a>
									</li>
								}



							</ul>
						</nav>
					</div>

					<!-- Social -->
					<div class="social flex-w flex-l-m p-r-20">

						<button class="btn-show-sidebar m-l-33 trans-0-4"></button>
					</div>
				</div>
			</div>
		</div>
	</header>

	<!-- Sidebar -->
	<aside class="sidebar trans-0-4">
		<!-- Button Hide sidebar -->
		<button class="btn-hide-sidebar ti-close color0-hov trans-0-4"></button>

		<!-- - -->
		<ul class="menu-sidebar p-t-95 p-b-70">
			<li class="t-center m-b-13">
				<a asp-area="Customer" asp-controller="Home" asp-action="Index" class="txt19">HOME</a>
			</li>

			<li class="t-center m-b-13">
				<a asp-area="Customer" asp-controller="Home" asp-action="Menu" class="txt19">MENU</a>
			</li>

			<li class="t-center m-b-13">
				<a asp-area="Customer" asp-controller="Home" asp-action="Gallery" class="txt19">GALLERY</a>
			</li>

			<li class="t-center m-b-13">
				<a asp-area="Customer" asp-controller="Home" asp-action="About" class="txt19">ABOUT</a>
			</li>

			<li class="t-center m-b-13">
				<a asp-area="Customer" asp-controller="Home" asp-action="Blog" class="txt19">BLOG</a>
			</li>

			<li class="t-center m-b-33">
				<a asp-area="Customer" asp-controller="Home" asp-action="Contact" class="txt19">CONTACT</a>
			</li>

			<li class="t-center">
				<!-- Button3 -->
				<a asp-area="Customer" asp-controller="Home" asp-action="Reservation" class="btn3 flex-c-m size13 txt11 trans-0-4 m-l-r-auto">
					Reservation
				</a>
			</li>
			<br />
			@if (User.Identity.IsAuthenticated)
			{
				<li class ="t-center m-b-33">
					<a asp-area="Admin" asp-controller="Menu" asp-action="Index" target="_blank" class="txt19">ADMIN PANEL</a>
				</li>
				<li class="t-center">
					<form class="btn3 flex-c-m size13 txt11 trans-0-4 m-l-r-auto" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
						<button type="submit" class="nav-link btn btn-link text-white">LOG OUT</button>
					</form>
				</li>
			}
		</ul>

		<!-- - -->
		
	</aside>

	@RenderBody()

	<!-- Welcome -->
	

	<!-- Footer -->
	<footer class="bg1">
		<div class="container p-t-40 p-b-70">
			<div class="row">
				<div class="col-sm-6 col-md-4 p-t-50">
					<!-- - -->
					<h4 class="txt13 m-b-33">
						Contact Us
					</h4>

					@await Component.InvokeAsync("Contact2")

					<!-- - -->
					
				</div>

				<div class="col-sm-6 col-md-4 p-t-50">
					

					<h4 class="txt13 m-b-32">
						Opening Times
					</h4>

					<ul>
						<li class="txt14">
							Every Day
						</li>

						<li class="txt14">
							09.00 AM - 11.00 PM 
						</li>
					</ul>
				</div>

				<div class="col-sm-6 col-md-4 p-t-50">
					<!-- - -->
					<h4 class="txt13 m-b-32">
						Social Media
					</h4>
					<div class="p-t-5 p-b-5">
						<a href="https://www.instagram.com/buonobuonopizza/" target="_blank" class="fs-15 c-white"><i class="fa fa-instagram" aria-hidden="true"></i></a>
						<a href="https://www.facebook.com/BuonoBuonoUAE/?locale=tr_TR"target="_blank" class="fs-15 c-white"><i class="fa fa-facebook m-l-18" aria-hidden="true"></i></a>
						<a href="https://x.com/BuonoBuonoo" class="fs-15 c-white"><i class="fa fa-twitter m-l-18" aria-hidden="true"></i></a>
					</div>


					

				</div>
			</div>
		</div>

		<div class="end-footer bg2">
			<div class="container">
				<div class="flex-sb-m flex-w p-t-22 p-b-22">
					

					<div class="txt17 p-r-20 p-t-5 p-b-5">
					 <a asp-area="Identity" asp-page="/Account/Login" target="_blank">BUONO BUONO</a>
					</div>
				</div>
			</div>
		</div>
	</footer>


	<!-- Back to top -->
	<div class="btn-back-to-top bg0-hov" id="myBtn">
		<span class="symbol-btn-back-to-top">
			<i class="fa fa-angle-double-up" aria-hidden="true"></i>
		</span>
	</div>

	<!-- Container Selection1 -->
	<div id="dropDownSelect1"></div>

	<!-- Modal Video 01-->
	<div class="modal fade" id="modal-video-01" tabindex="-1" role="dialog" aria-hidden="true">

		<div class="modal-dialog" role="document" data-dismiss="modal">
			<div class="close-mo-video-01 trans-0-4" data-dismiss="modal" aria-label="Close">&times;</div>

			<div class="wrap-video-mo-01">
				<div class="w-full wrap-pic-w op-0-0"><img src="/Site/images/icons/video-16-9.jpg" alt="IMG"></div>
				<div class="video-mo-01">
					<iframe src="https://www.youtube.com/embed/5k1hSu2gdKE?rel=0&amp;showinfo=0" allowfullscreen></iframe>
				</div>
			</div>
		</div>
	</div>



	<!--===============================================================================================-->
	<script type="text/javascript" src="/Site/vendor/jquery/jquery-3.2.1.min.js"></script>
	<!--===============================================================================================-->
	<script type="text/javascript" src="/Site/vendor/animsition/js/animsition.min.js"></script>
	<!--===============================================================================================-->
	<script type="text/javascript" src="/Site/vendor/bootstrap/js/popper.js"></script>
	<script type="text/javascript" src="/Site/vendor/bootstrap/js/bootstrap.min.js"></script>
	<!--===============================================================================================-->
	<script type="text/javascript" src="/Site/vendor/select2/select2.min.js"></script>
	<!--===============================================================================================-->
	<script type="text/javascript" src="/Site/vendor/daterangepicker/moment.min.js"></script>
	<script type="text/javascript" src="/Site/vendor/daterangepicker/daterangepicker.js"></script>
	<!--===============================================================================================-->
	<script type="text/javascript" src="/Site/vendor/slick/slick.min.js"></script>
	<script type="text/javascript" src="/Site/js/slick-custom.js"></script>
	<!--===============================================================================================-->
	<script type="text/javascript" src="/Site/vendor/parallax100/parallax100.js"></script>
	<script type="text/javascript">
		$('.parallax100').parallax100();
	</script>
	<!--===============================================================================================-->
	<script type="text/javascript" src="/Site/vendor/countdowntime/countdowntime.js"></script>
	<!--===============================================================================================-->
	<script type="text/javascript" src="/Site/vendor/lightbox2/js/lightbox.min.js"></script>
	<!--===============================================================================================-->
	<script src="/Site/js/main.js"></script>
	@await RenderSectionAsync("Scripts", required: false)
	@await Component.InvokeAsync("NToastNotify")

</body>
</html>

CafeRestaurant_/Views/Shared/_Layout.cshtml
@using CafeRestaurant_.Models
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BUONO BUONO </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https: //cdn.datatables.net/2.2.2/css/dataTables.dataTables.min.css">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                @if (User.Identity.IsAuthenticated)
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" target="_blank"> WebSite  </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Menu" asp-action="Index">Menu</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Reservation" asp-action="Index">Reservation</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Gallery" asp-action="Index">Gallery</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="About" asp-action="Index">About</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Blog" asp-action="Index">Comments</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Contact" asp-action="Index">Messages</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Contact2" asp-action="Index">Contact</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="User" asp-action="Index">Users</a>
                            </li>
                        </ul>
                        <partial name="_LoginPartial" />
                    </div>
                }
                else
                {
                    
                }

               
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - CafeRestaurant_ - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/2.2.2/js/dataTables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>